#!/bin/sh

case $(uname -m) in
   x86_64);;
   *) echo "This script is intended to be executed on a x86_64 system."
      echo "Running it on another platform probably doesn't work unless"
      echo "a cross compiler is installed (and this script is modified"
      echo "to reflect this)."
      exit 1;;
esac

clear
rm sample

echo --------------------------------------------------------------------------
gcc -DLINUX ../../../sample.c -I../../.. -Wl,-rpath,'$ORIGIN' libsntl_licgen_linux_x86_64.so -lpthread -o sample
ls -l sample

echo
sync

