#!/bin/sh

clear
rm hasp_demo
rm hasp_update

echo --------------------------------------------------------------------------
/opt/hisi-linux/x86-arm/arm-hisiv500-linux/bin/arm-hisiv500-linux-uclibcgnueabi-gcc ../../../hasp_demo.c -I../../.. libhasp_linux_armuclibc_demo.a -lpthread -o hasp_demo
ls -l hasp_demo
echo --------------------------------------------------------------------------
/opt/hisi-linux/x86-arm/arm-hisiv500-linux/bin/arm-hisiv500-linux-uclibcgnueabi-gcc ../../../hasp_update.c -I../../.. libhasp_linux_armuclibc_demo.a -lpthread -o hasp_update
ls -l hasp_update
echo --------------------------------------------------------------------------

echo
sync

