#!/bin/sh

clear
rm hasp_demo
rm hasp_update

echo --------------------------------------------------------------------------
arm-linux-gnueabi-gcc ../../../hasp_demo.c -I../../.. libhasp_linux_armel_demo.a -lpthread -o hasp_demo
ls -l hasp_demo
echo --------------------------------------------------------------------------
arm-linux-gnueabi-gcc ../../../hasp_update.c -I../../.. libhasp_linux_armel_demo.a -lpthread -o hasp_update
ls -l hasp_update
echo --------------------------------------------------------------------------

echo
sync

