#!/bin/sh

clear
rm hasp_demo
rm hasp_update

echo --------------------------------------------------------------------------
arm-linux-gnueabi-gcc ../../../hasp_demo.c -I../../.. -Wl,-rpath,'$ORIGIN' libhasp_linux_armel_demo.so -lpthread -o hasp_demo
ls -l hasp_demo
echo --------------------------------------------------------------------------
arm-linux-gnueabi-gcc ../../../hasp_update.c -I../../.. -Wl,-rpath,'$ORIGIN' libhasp_linux_armel_demo.so -lpthread -o hasp_update
ls -l hasp_update
echo --------------------------------------------------------------------------

echo
sync

